apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gradle-hello
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gradle-hello
    spec:
      containers:
        - name: gradle-hello
          image: image-registry.openshift-image-registry.svc:5000/default/gradle-hello
          env:
            - name: BUILD_PROFILE
              value: test
          ports:
            - name: http-api
              containerPort: 8080
